import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'
import { getLocale } from './getLocale'
import { fromNow } from './date-utils'
import Link from 'next/link'
import { setupServerGlobals } from './setupServerGlobals'
import { changeLanguage } from './actions'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const linkStyle: React.CSSProperties = {
  display: 'inline-flex',
  padding: 12,
  backgroundColor: 'lightcoral',
  color: 'white',
  borderRadius: 8,
}

const localeButtonStyle = (isActive: boolean = false): React.CSSProperties => ({
  padding: '12px 16px',
  backgroundColor: isActive ? 'lightgreen' : 'white',
  borderRadius: 8,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  setupServerGlobals()
  const locale = getLocale()

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers locale={locale}>
          <header style={{ display: 'flex', gap: 32 }}>
            <div style={{ display: 'flex', gap: 12 }}>
              <Link href="/page-1" style={linkStyle}>
                Page 1
              </Link>
              <Link href="/page-2" style={linkStyle}>
                Page 2
              </Link>
            </div>

            {/* lol don’t mind the pattern, experimenting */}
            <div style={{ display: 'flex', gap: 8 }}>
              <form action={changeLanguage.bind(null, 'en')}>
                <button
                  type="submit"
                  disabled={locale === 'en'}
                  style={localeButtonStyle(locale === 'en')}
                >
                  EN
                </button>
              </form>
              <form action={changeLanguage.bind(null, 'id')}>
                <button
                  type="submit"
                  disabled={locale === 'id'}
                  style={localeButtonStyle(locale === 'id')}
                >
                  ID
                </button>
              </form>
            </div>
          </header>

          <br />

          <div>Layout: 2022 - {fromNow('2022-01-01')}</div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
